# Generated by Django 3.1.4 on 2021-05-01 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.CreateModel(
            name='UserPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.pizzasize')),
                ('toppings', models.ManyToManyField(to='store.Toppings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
