# Generated by Django 3.1.4 on 2021-05-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_toppings_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
