# Generated by Django 3.1.4 on 2021-05-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_type',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='userpizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='userpizza',
            name='extra_toppings',
            field=models.ManyToManyField(blank=True, null=True, to='store.Toppings'),
        ),
        migrations.AddField(
            model_name='userpizza',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
