# Generated by Django 3.1.4 on 2021-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210501_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='topping_name',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='user',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppings',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.DeleteModel(
            name='UserPizza',
        ),
    ]
