# Generated by Django 3.1.4 on 2021-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passwordchanged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
